# -------------------------------------------
# Wutong-Console:
# -------------------------------------------

# Refer to README for configuration details
# Please refer to the official documentation for installation https://www.wutong.com/docs/install/other-methods/install-from-rancher/

# Specify up the dynamic storage used by the Wutong component
# If not, please refer https://artifacthub.io/packages/helm/kvaps/nfs-server-provisioner
pvc:
  storageClassName: ""
  # 5Gi
  storageSize: 5Gi

# Redis configuration,Refer to README for configuration details
redis:
  # Specify the full name of Redis
  fullname: wutong-redis

  # Specify the Redis image
  image:
    repository: redis
    pullPolicy: IfNotPresent
    tag: 5.0

  # Specify the Redis Password
  password: "123456"
  podAnnotations: {}

  # Set the Redis Labels
  selectorLabels:
    wutong: redis

  # Set POD resource limits
  resources:
    limits:
      cpu: 80m
      memory: 64Mi
    requests:
      cpu: 30m
      memory: 64Mi

  nodeSelector: {}
  affinity: {}

# Mysql configuration,Refer to README for configuration details
mysql:
  # Specify the full name of Mysql
  fullname: wutong-mysql

  # Specify the Mysql image
  image:
    repository: mysql
    pullPolicy: IfNotPresent
    tag: 8.0

  # Specify your MySQL account password and database
  secret:
    user: admin
    password: admin
    rootpassword: root
    database: console

  podAnnotations: {}

  # Set the MySQL Labels
  selectorLabels:
    wutong: mysql

  # Set POD resource limits
  resources:
    limits:
      cpu: 640m
      memory: 512Mi
    requests:
      cpu: 120m
      memory: 512Mi

  nodeSelector: {}
  affinity: {}

# Separate versions of the front and back ends of Wutong-Console
# Cluster installation controller configuration
# Deprecated, please refer to the official documentation to install the detached console from the Wutong-Paas Store https://www.wutong.com/docs/user-operations/ha-deploy/console-recover/
adaptor:
  # Specify the full name of adaptor
  fullname: wutong-adaptor

  # Adaptor is not installed by default
  enable: true

  # Specify the Adaptor image
  # No mirroring is provided by default
  image:
    repository: "swr.cn-southwest-2.myhuaweicloud.com/wutong/wutong-adaptor"
    pullPolicy: IfNotPresent
    tag: "v1.2.0-stable"

  podAnnotations: {}

  # Set the Adaptor Labels
  selectorLabels:
    wutong: adaptor

  # Set POD resource limits
  resources:
    limits:
      cpu: 480m
      memory: 512Mi
    requests:
      cpu: 120m
      memory: 128Mi

  nodeSelector: {}
  affinity: {}

# Separate versions of the front and back ends of Wutong-Console
# Console back-end services
# Deprecated, please refer to the official documentation to install the detached console from the Wutong-Paas Store https://www.wutong.com/docs/user-operations/ha-deploy/console-recover/
console:
  # Specify the full name of Console
  fullname: wutong-console

  # Console is not installed by default
  enable: true

  # Set the number of copies
  replicasCount: 1

  # Specify the Console image
  # No mirroring is provided by default
  image:
    repository: "swr.cn-southwest-2.myhuaweicloud.com/wutong/wutong-console"
    pullPolicy: IfNotPresent
    tag: "v1.2.0-stable"

  podAnnotations: {}

  # Set the Console Labels
  selectorLabels:
    wutong: console

  # Set POD resource limits
  resources:
    limits:
      cpu: 1280m
      memory: 4Gi
    requests:
      cpu: 240m
      memory: 1Gi

  nodeSelector: {}
  affinity: {}

# Separate versions of the front and back ends of Wutong-Console
# Console front-end services
# Deprecated, please refer to the official documentation to install the detached console from the Wutong-Paas Store https://www.wutong.com/docs/user-operations/ha-deploy/console-recover/
ui:
  # Specify the full name of UI
  fullname: wutong-ui

  # UI is not installed by default
  enable: true

  # Set the number of copies
  replicasCount: 1

  # Specify the Console image
  # No mirroring is provided by default
  image:
    repository: "swr.cn-southwest-2.myhuaweicloud.com/wutong/wutong-ui"
    pullPolicy: IfNotPresent

    tag: "v1.2.0-stable"

  domain: console.wutongpaas.com

  # The default service protocol is NodePort, which opens port 30606
  svc:
    type: NodePort
    nodePort: 30600

  podAnnotations: {}

  # Set the UI Labels
  selectorLabels:
    wutong: ui

  # Set POD resource limits
  resources:
    limits:
      cpu: 120m
      memory: 512Mi
    requests:
      cpu: 30m
      memory: 128Mi

  nodeSelector: {}
  affinity: {}
