
{{- if .Values.Cluster.RWO.enable  }}
apiVersion: wutong.io/v1alpha1
kind: WutongVolume
metadata:
  labels:
    accessModes: rwo
    belongTo: wutong-operator
    creator: Wutong
  name: wutongvolumerwo
  namespace: wt-system
spec:
  storageClassName: {{ .Values.Cluster.RWO.storageClassName }}
  imageRepository: swr.cn-southwest-2.myhuaweicloud.com/wutong
{{- end }}
  