{{- if .Values.console.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.console.fullname }}
  labels:
    wutong: console
    creator: Wutong
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    wutong: console
{{- end }}