apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.fullname }}-pvc
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}