apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.fullname }}-secret
  labels:
    wutong: redis-pass
    creator: Wutong
type: Opaque
data:
  REDISC_REQUIREPASS: {{ .Values.redis.password | b64enc }}