{{- if .Values.ui.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: wutong-ui-cm
data:
  # 类文件键
  default.conf: |
    server {
      listen 80;
    
      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      location /static/dists/ {
          root  /usr/share/nginx/html;
          rewrite ^/static/dists/(.*)$ /$1 break;
      }

      location /console/proxy {
          proxy_pass http://{{ .Values.adaptor.fullname }}:8080;
          rewrite ^/console/proxy/(.*)$ /$1 break;
      }

      location /console {
          proxy_pass http://{{ .Values.console.fullname }}:8888;
      }

      location /static/www {
          proxy_pass http://{{ .Values.console.fullname }}:8888;
      }

      location /data {
          proxy_pass http://{{ .Values.console.fullname }}:8888;
      }

      location /openapi {
          proxy_pass http://{{ .Values.console.fullname }}:8888;
      }
    }
{{- end }}