{{- if .Values.ui.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ui.fullname }}
  labels:
    wutong: ui
spec:
  replicas: {{ .Values.ui.replicasCount }}
  selector:
  {{- with .Values.ui.selectorLabels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  template:
    metadata:
    {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ui.selectorLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
            - name: TZ
              value: "Asia/Shanghai"
          ports:
            - name: tcp
              containerPort: 80
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /console/config/info
              port: 80
              scheme: HTTP
            initialDelaySeconds: 4
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
            name: ui-conf
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      volumes:
      - name: ui-conf
        configMap:
          name: wutong-ui-cm
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}