{{- if .Values.console.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ui.fullname }}
  labels:
    wutong: console
spec:
  rules:
  - host: {{ .Values.ui.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ui.fullname }}
            port:
              number: 80
{{- end }}