{{- if .Values.ui.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: wutong-ui-cm
data:
  # 类文件键
  web.conf: |
    server {
      listen 6000;
    
      location / {
          root   /app/www;
          index  index.html index.htm;
      }

      location /static/dists/ {
          root  /app/www;
          rewrite ^/static/dists/(.*)$ /$1 break;
      }
      
      location /console {
          proxy_pass http://{{ .Values.console.fullname }}:5000;
      }

      location /static/www {
          proxy_pass http://{{ .Values.console.fullname }}:5000;
      }

      location /data {
          proxy_pass http://{{ .Values.console.fullname }}:5000;
      }

      location /openapi {
          proxy_pass http://{{ .Values.console.fullname }}:5000;
      }
    }
{{- end }}