{{- if .Values.ui.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.fullname }}
  labels:
    wutong: ui
spec:
  type: {{ .Values.ui.svc.type }}
  selector:
    wutong: ui
  ports:
    - port: 6000
      targetPort: 6000
      {{ if eq .Values.ui.svc.type "NodePort" }}
      nodePort: {{ .Values.ui.svc.nodePort }}
      {{ end }}
{{- end }}